# Generated by Django 4.2.5 on 2023-10-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=55, verbose_name='Category Slug')),
            ],
        ),
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=150, verbose_name='Food Title')),
                ('slug', models.SlugField(max_length=160, verbose_name='Food Slug')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='Unique Food ID (SKU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsuoc.category', verbose_name='Product Categoy')),
            ],
        ),
    ]
