# Generated by Django 4.2.5 on 2023-10-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmsuoc', '0003_cart_product_delete_foodlist_cart_food_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food',
            new_name='product',
        ),
    ]
